// <auto-generated />
using System;
using DespesaViagem.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DespesaViagem.Infra.Migrations
{
    [DbContext(typeof(DespesaViagemContext))]
    [Migration("20231124141043_criacao-sqlite")]
    partial class criacaosqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("DespesaViagem.Shared.Models.Core.Helpers.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Core.Helpers.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Core.Helpers.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("TipoDeUsuario")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator<int>("TipoDeUsuario").HasValue(2);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Despesas.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataDespesa")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoDespesa")
                        .IsRequired()
                        .HasColumnType("varchar(3000)");

                    b.Property<int>("IdViagem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeDespesa")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("TipoDespesa")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("TotalDespesa")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdViagem");

                    b.ToTable("Despesas");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Viagens.Viagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Adiantamento")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal");

                    b.Property<DateTime>("DataFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicial")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoViagem")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(3000)");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeViagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("StatusViagem")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar");

                    b.Property<decimal>("TotalDespesas")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("Viagens", (string)null);
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Core.Helpers.Funcionario", b =>
                {
                    b.HasBaseType("DespesaViagem.Shared.Models.Core.Helpers.Usuario");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GestorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .HasColumnType("varchar(30)");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("GestorId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Core.Helpers.Gestor", b =>
                {
                    b.HasBaseType("DespesaViagem.Shared.Models.Core.Helpers.Usuario");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Despesas.DespesaAlimentacao", b =>
                {
                    b.HasBaseType("DespesaViagem.Shared.Models.Despesas.Despesa");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeEstabelecimento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorRefeicao")
                        .HasColumnType("decimal(10,2)");

                    b.ToTable("DespesasAlimentacao", (string)null);
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Despesas.DespesaDeslocamento", b =>
                {
                    b.HasBaseType("DespesaViagem.Shared.Models.Despesas.Despesa");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<long>("Quilometragem")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ValorPorQuilometro")
                        .HasColumnType("decimal(10,2)");

                    b.ToTable("DespesasDeslocamento", (string)null);
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Despesas.DespesaHospedagem", b =>
                {
                    b.HasBaseType("DespesaViagem.Shared.Models.Despesas.Despesa");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("NumeroCasa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeDias")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("decimal(10,2)");

                    b.ToTable("DespesasHospedagem", (string)null);
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Despesas.DespesaPassagem", b =>
                {
                    b.HasBaseType("DespesaViagem.Shared.Models.Despesas.Despesa");

                    b.Property<string>("Companhia")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraEmbarque")
                        .HasColumnType("datetime");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.ToTable("DespesasPassagem", (string)null);
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Core.Helpers.Endereco", b =>
                {
                    b.HasOne("DespesaViagem.Shared.Models.Despesas.DespesaHospedagem", "DespesaHospedagem")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DespesaHospedagem");
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Despesas.Despesa", b =>
                {
                    b.HasOne("DespesaViagem.Shared.Models.Viagens.Viagem", "Viagem")
                        .WithMany("Despesas")
                        .HasForeignKey("IdViagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Viagens.Viagem", b =>
                {
                    b.HasOne("DespesaViagem.Shared.Models.Core.Helpers.Funcionario", "Funcionario")
                        .WithMany("Viagens")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Core.Helpers.Funcionario", b =>
                {
                    b.HasOne("DespesaViagem.Shared.Models.Core.Helpers.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("DespesaViagem.Shared.Models.Core.Helpers.Gestor", "Gestor")
                        .WithMany("Funcionarios")
                        .HasForeignKey("GestorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departamento");

                    b.Navigation("Gestor");
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Despesas.DespesaAlimentacao", b =>
                {
                    b.HasOne("DespesaViagem.Shared.Models.Despesas.Despesa", null)
                        .WithOne()
                        .HasForeignKey("DespesaViagem.Shared.Models.Despesas.DespesaAlimentacao", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Despesas.DespesaDeslocamento", b =>
                {
                    b.HasOne("DespesaViagem.Shared.Models.Despesas.Despesa", null)
                        .WithOne()
                        .HasForeignKey("DespesaViagem.Shared.Models.Despesas.DespesaDeslocamento", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Despesas.DespesaHospedagem", b =>
                {
                    b.HasOne("DespesaViagem.Shared.Models.Despesas.Despesa", null)
                        .WithOne()
                        .HasForeignKey("DespesaViagem.Shared.Models.Despesas.DespesaHospedagem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Despesas.DespesaPassagem", b =>
                {
                    b.HasOne("DespesaViagem.Shared.Models.Despesas.Despesa", null)
                        .WithOne()
                        .HasForeignKey("DespesaViagem.Shared.Models.Despesas.DespesaPassagem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Viagens.Viagem", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Core.Helpers.Funcionario", b =>
                {
                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("DespesaViagem.Shared.Models.Core.Helpers.Gestor", b =>
                {
                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
